### ISSUE TITLE
fill_dates.R generates wildly incorrect dates

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#171]
ISRaD.extra.fill_dates.R seems to be incorrectly filling inc_obs_date_y from lyr_obs_date_y with dates that are sometimes extremely different.

Examples (should match)
Dutta_2006: 
template: lyr_obs_date_y = 2001, inc_obs_date_y is blank
ISRaD_extra: inc_obs_date_y = 1983 (should be filled from lyr_obs_date_y)

Taylor_2015: 
template: lyr_obs_date_y = 2012 or 2013, inc_obs_date_y is blank
ISRaD_extra: inc_obs_date_y = 2012, 1998, 1970, 1971, 1986 (should be filled from lyr_obs_date_y)

In total there are 267 profiles with a inc_date vs lyr_date mismatch in ISRaD_extra, which are sometimes extremely different. In ISRaD_data, there are 62 date mismatches, but normally all different by 1-2yrs, which is reasonable (eg samples collected in 2001, incubated in 2002). 

I don't see any obvious reason this date mismatch is being introduced. Also, this could be accounting for or related to our issues with the ISRaD_extra delta delta function, which was also never fixed.

**Comment by greymonroe** [comment]
The fill date function looked wrong. it wasnt doing any matching between the layer and fraction tab for example. just basically saying if the frc date was NA then make it a value from lyr date but not specifying which one. I am making the correction now.

**Comment by jb388** [comment]
Nice catch, Grey. Hopefully this fixes it!

**Comment by aahoyt** [comment]
Thanks Grey! Let me know when it's updated & I will check the delta delta calculations

**Comment by greymonroe** [comment]
Ok can you check now?

**Comment by aahoyt** [comment]
checking now

**Comment by aahoyt** [comment]
Based on my checks, the date issue doesn't seem to be fixed. Here's my code to check with a figure. Dates should fall mostly along the 1:1 line
#Check date issue:
inc_data_check <- ISRaD_extra$incubation %>% #Start with incubation data
  left_join(ISRaD_extra$layer)  #Join to layer data
ggplot()+
  geom_point(data = inc_data_check, aes(x = inc_obs_date_y, y = lyr_obs_date_y), size = 5)+
  theme_bw()
![filldateissue](https://user-images.githubusercontent.com/5949455/53301902-7738cf00-3858-11e9-82a2-561d3ad5a442.png)

And in case I just wasn't able to update the package for some reason, I downloaded the ISRaD_extra file and searched for Dutta_2006 on the incubation tab (inc_obs_date_y still says 1983 instead of 2001)
https://international-soil-radiocarbon-database.github.io/ISRaD/database/

**Comment by greymonroe** [comment]
ok it should be fixed now, but lets double check.

<img width="536" alt="screen shot 2019-02-24 at 1 37 58 pm" src="https://user-images.githubusercontent.com/16675068/53303548-85c3be00-3839-11e9-8160-b5e5a55c9456.png">

**Comment by aahoyt** [comment]
Yes, looks fixed to me too. Thanks!

The only study where the incubation date is now earlier than the layer date (how do you incubate a sample before you collect it?) is Czimczik_2007 (but issue comes from the template, not the function)

**Comment by aahoyt** [comment]
However, the filled frc_obs_date_y looks like perhaps it is still having a similar, but less widespread issue?

(red is original, black is filled, so we would expect all black along the 1:1 line)

Example study with issues to check is Baisden_2002. Blank frc_obs_date_y from profiles Riverbank1997 (lyr_obs_date_y = 1997) get filled to 1949 (looks like a value for other fractions on the same template) instead of 1997.
![frc_date_fill](https://user-images.githubusercontent.com/5949455/53306102-373e1000-3889-11e9-9175-5bd61d385906.png)

**Comment by aahoyt** [comment]
Also, we should check to see if the various other fill functions are facing similar issues...

**Comment by greymonroe** [comment]
ok. see fig1 for new filled dates. should be correct now (at least the fill part, there are still some inconstancies that might be some errors in the datasheets).

<img width="528" alt="screen shot 2019-02-24 at 7 24 33 pm" src="https://user-images.githubusercontent.com/16675068/53307882-b3752b00-386a-11e9-9284-92af8ba5091b.png">



below are the latitudes and longitudes. There appear to be some issues, but i checked and it doesnt seem to be caused by the fill function.

<img width="527" alt="screen shot 2019-02-24 at 7 29 12 pm" src="https://user-images.githubusercontent.com/16675068/53307883-b3752b00-386a-11e9-9e05-a010153ce9ff.png">
<img width="527" alt="screen shot 2019-02-24 at 7 29 12 pm" src="https://user-images.githubusercontent.com/16675068/53307886-b5d78500-386a-11e9-99be-533c508fb102.png">

**Comment by alkalifly** [comment]
For the longitudes, the location of some of those dots (the ones that are way off) looks like a missing or spurious negative sign

**Comment by greymonroe** [comment]
@alkalifly yep youre probably right. do we want to manually change these?

**Comment by jb388** [comment]
Just to note that there are some entries that have different pro_lat/pro_long than site_lat/site_long (i.e. they shouldn't line up on the 1:1 line).

**Comment by greymonroe** [comment]
This is fixed
